provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  render:
    lang: python3
    handler: ./render
    image: render
    environment:
      content_type: text/html
      assets_url: "/" # set to "/function/" when deploying locally

  assets:
    lang: python3
    handler: ./assets
    image: assets
    environment:
      content_type: application/json

